---
namespace: dummy-test-app-dev

nameSuffix: "-dev"

resources:
  - ../../base
  - namespace.yml

secretGenerator:
  - name: secret-dummy-test-app
    envs:
    - secret/dummy-test-app.env

patches:
  - target:
      kind: Ingress
      name: dummy-test-app-ingress
    path: patch/ingress-patch.yml

images:
  - name: dummy-test-app
    newName: leniyou/dummy-test-exam
    newTag: latest
